# Generated by Django 4.2.30 on 2026-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('battery_type', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('hiring', 'Hiring'), ('buying', 'Buying')], max_length=20)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
