# Generated by Django 6.0.5 on 2026-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('parking_slot', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('signed_out', models.BooleanField(default=False)),
            ],
        ),
    ]
