# Generated by Django 4.2.30 on 2026-05-21 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('signed_out', models.BooleanField(default=False)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('receiver_nin', models.CharField(blank=True, max_length=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
