# Generated by Django 6.0.5 on 2026-05-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('tyre_size', models.CharField(max_length=20)),
                ('tyre_model', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('pressure_check', 'Pressure Check'), ('puncture_repair', 'Puncture Repair'), ('tyre_replacement', 'Tyre Replacement'), ('valve_replacement', 'Valve Replacement'), ('wheel_balancing', 'Wheel Balancing')], max_length=20)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
