# Generated by Django 4.2.30 on 2026-05-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_alter_tyreservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
